(()=>{'use strict';
const $=id=>document.getElementById(id),canvas=$('canvas'),ctx=canvas.getContext('2d'),stage=$('stage');
const ui={score:$('score'),hearts:$('hearts'),start:$('start'),restart:$('restart'),overlay:$('overlay'),play:$('play'),title:$('overlay-title'),copy:$('overlay-copy'),badge:$('overlay-badge'),tip:$('overlay-tip'),status:$('status'),announcer:$('announcer'),sound:$('sound')};
const H=620;let W=1000,mode='ready',score=0,lives=3,items=[],particles=[],popups=[],playerX=500,previousX=500,walk=0,clock=0,lastTime=0,nextDrop=.9,hurt=0,throwTime=0,squirrelX=500,squirrelTarget=500,audioCtx=null,soundOn=false,pointerTarget=null,dragging=false,pausedForHidden=false;
const keys=new Set(),held=new Map();const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const rnd=(a,b)=>a+Math.random()*(b-a),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function ellipse(x,y,rx,ry,fill){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();}
function path(points,fill,stroke,width=2){ctx.beginPath();for(let i=0;i<points.length;i++){let p=points[i];if(i===0)ctx.moveTo(...p);else ctx.lineTo(...p);}ctx.closePath();if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}
function line(x1,y1,x2,y2,color,width=3){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.stroke();}
function round(x,y,w,h,r,fill){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill();}
function apple(x,y,r=16,angle=0,face=false){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(r/16,r/16);line(0,-12,2,-24,'#785541',3);ctx.save();ctx.translate(4,-19);ctx.rotate(-.45);ellipse(0,0,9,4,'#7c9c4a');ctx.restore();ctx.fillStyle='#ee7966';ctx.beginPath();ctx.moveTo(0,-11);ctx.bezierCurveTo(-22,-25,-24,4,-12,15);ctx.bezierCurveTo(-5,22,-2,15,0,17);ctx.bezierCurveTo(5,23,18,16,20,2);ctx.bezierCurveTo(23,-16,10,-21,0,-11);ctx.fill();ctx.beginPath();ctx.moveTo(-12,-5);ctx.quadraticCurveTo(-16,0,-11,6);ctx.strokeStyle='#ffb696';ctx.lineWidth=3;ctx.lineCap='round';ctx.stroke();if(face){ellipse(-6,1,1.5,2,'#704637');ellipse(7,1,1.5,2,'#704637');ctx.beginPath();ctx.arc(.5,5,3,0,Math.PI);ctx.strokeStyle='#704637';ctx.lineWidth=1.5;ctx.stroke();}ctx.restore();}
function chestnut(x,y,r=19,angle=0){ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.scale(r/19,r/19);const spikes=[];for(let i=0;i<32;i++){let a=i*Math.PI/16,rr=i%2?17:25;spikes.push([Math.cos(a)*rr,Math.sin(a)*rr]);}path(spikes,'#879952');ellipse(0,0,18,18,'#a9b770');ctx.beginPath();ctx.moveTo(0,-14);ctx.bezierCurveTo(-22,0,-15,15,0,15);ctx.bezierCurveTo(20,14,17,-3,0,-14);ctx.fillStyle='#9b6649';ctx.fill();ctx.beginPath();ctx.moveTo(-13,8);ctx.quadraticCurveTo(0,18,14,8);ctx.lineTo(10,14);ctx.quadraticCurveTo(0,20,-11,14);ctx.fillStyle='#d9af7a';ctx.fill();line(-4,-5,-7,0,'#c99766',2);ctx.restore();}
function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ellipse(-31,2,29,16,'#fffdf3bb');ellipse(0,-10,30,24,'#fffdf3bb');ellipse(31,1,32,16,'#fffdf3bb');ctx.restore();}
function flower(x,y,s,color){ctx.save();ctx.translate(x,y);ctx.scale(s,s);line(0,0,-2,-15,'#8ca45e',2);for(let i=0;i<5;i++){let a=i*Math.PI*2/5;ellipse(Math.cos(a)*4,-17+Math.sin(a)*4,3.2,3.2,color);}ellipse(0,-17,2.4,2.4,'#f0c262');ctx.restore();}
function background(){const grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#dceecd');grad.addColorStop(.6,'#eaf2d7');grad.addColorStop(1,'#dae8b9');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);ellipse(W*.15,118,43,43,'#fff0b780');cloud(W*.18+Math.sin(clock*.03)*8,159,.8);cloud(W*.71,207,.95);ctx.beginPath();ctx.moveTo(0,430);ctx.bezierCurveTo(W*.22,328,W*.42,457,W*.63,393);ctx.bezierCurveTo(W*.8,349,W*.95,398,W,368);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fillStyle='#cfdfad';ctx.fill();ctx.beginPath();ctx.moveTo(0,483);ctx.bezierCurveTo(W*.3,399,W*.43,473,W*.74,443);ctx.bezierCurveTo(W*.87,422,W*.94,448,W,427);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fillStyle='#bbd39b';ctx.fill();
// Orchard fence behind the player.
for(let x=12;x<W;x+=59){round(x,439,9,72,4,'#e8e1be');path([[x,440],[x+4.5,434],[x+9,440]],'#e8e1be');}round(0,456,W,7,2,'#eee7c8');round(0,483,W,7,2,'#eee7c8');
const trunkX=W*.84;ctx.beginPath();ctx.moveTo(trunkX-29,0);ctx.bezierCurveTo(trunkX-26,135,trunkX+5,260,trunkX-15,475);ctx.lineTo(trunkX+62,475);ctx.bezierCurveTo(trunkX+48,245,trunkX+25,111,trunkX+47,0);ctx.fillStyle='#ba9970';ctx.fill();line(trunkX+12,40,trunkX+27,400,'#a4815f',5);line(trunkX+16,171,W*.66,104,'#ba9970',25);line(trunkX+26,109,W*.95,42,'#ba9970',18);for(let k=0;k<4;k++)line(trunkX+39,238+k*44,trunkX+42,260+k*44,'#d1b087',3);
// A broad leafy canopy covers the random drop positions.
for(let i=0;i<8;i++){const x=(i/7)*W;ellipse(x,10+Math.sin(i*3)*16,W/6,78+i%3*12,'#86aa67');ellipse(x+18,42+Math.cos(i*2)*11,W/8,62,'#99b875');}for(let i=0;i<10;i++)ellipse((i+.4)*W/10,8+Math.sin(i*7)*17,W/13,43,'#acc985');for(let i=0;i<6;i++)apple((i+.65)*W/6,43+(i%3)*13,11,-.15+i*.05);
// The squirrel's branch.
line(squirrelX-63,113,squirrelX+65,113,'#967452',13);line(squirrelX-57,110,squirrelX+62,110,'#bd9666',5);
ctx.fillStyle='#aeca7f';ctx.beginPath();ctx.moveTo(0,558);ctx.quadraticCurveTo(W*.5,538,W,559);ctx.lineTo(W,H);ctx.lineTo(0,H);ctx.fill();ellipse(W*.5,581,W*.58,30,'#c5da95');for(let i=0;i<Math.ceil(W/57);i++){const x=i*57+14,y=582+(i%3)*8;line(x,y,x-3,y-9,'#96b36b',1.5);line(x,y,x+5,y-7,'#96b36b',1.5);}for(let i=0;i<Math.ceil(W/128);i++){flower(35+i*128,572+(i%2)*25,.8,i%2?'#fbefcf':'#f3b2a0');flower(72+i*128,601,.65,'#fff9e6');}
}
function squirrel(){ctx.save();ctx.translate(squirrelX,81);const bounce=reduceMotion?0:Math.sin(clock*3)*1.5;ctx.translate(0,bounce);ctx.beginPath();ctx.moveTo(-11,19);ctx.bezierCurveTo(-60,42,-70,-28,-39,-34);ctx.bezierCurveTo(-19,-39,-15,-17,-32,-16);ctx.bezierCurveTo(-49,-15,-29,8,-15,0);ctx.fillStyle='#b87b51';ctx.fill();ctx.beginPath();ctx.moveTo(-39,-25);ctx.bezierCurveTo(-55,-5,-37,19,-23,15);ctx.strokeStyle='#dfac7e';ctx.lineWidth=7;ctx.lineCap='round';ctx.stroke();ellipse(1,11,18,24,'#cb905e');ellipse(5,15,10,16,'#f1d2a0');path([[-14,-18],[-19,-43],[-3,-34],[0,-18]],'#cb905e');path([[7,-22],[18,-40],[25,-28],[21,-11]],'#cb905e');path([[-12,-29],[-15,-36],[-7,-32]],'#e8b390');ellipse(3,-15,22,19,'#d49b66');ellipse(17,-9,14,10,'#f3d8ab');ellipse(8,-22,3.1,3.7,'#514433');ellipse(8.7,-23.2,.9,.9,'#fff');ellipse(30,-12,2.6,2.3,'#614a35');ctx.beginPath();ctx.arc(20,-8,4,.2,2.3);ctx.strokeStyle='#956746';ctx.lineWidth=1.5;ctx.stroke();const armAngle=throwTime>0?-.95:-.18;ctx.save();ctx.translate(9,4);ctx.rotate(armAngle);ellipse(9,0,12,5,'#c58a58');if(throwTime>.18)apple(21,-5,8);ctx.restore();ellipse(-8,31,10,4,'#a36a45');ellipse(12,31,10,4,'#a36a45');ctx.restore();}
function player(){const x=playerX,y=H-57,bob=reduceMotion?0:Math.sin(walk)*Math.min(2.5,Math.abs(playerX-previousX)*.8);ctx.save();ctx.translate(x,y+bob);if(hurt>0&&Math.floor(hurt*13)%2===0)ctx.globalAlpha=.5;ellipse(11,5,50,9,'#64875128');const stride=Math.abs(playerX-previousX)>.3&&!reduceMotion?Math.sin(walk)*5:0;line(-10,-34,-14+stride,-4,'#806b58',10);line(8,-34,12-stride,-4,'#806b58',10);round(-23+stride,-7,20,10,5,'#685845');round(5-stride,-7,20,10,5,'#685845');round(-23,-91,45,59,13,'#eaa878');path([[-19,-78],[-8,-75],[-8,-34],[-23,-34]],'#d98465');line(1,-84,26,-61,'#aa7960',4);line(-15,-80,-28,-54,'#efc09b',11);ellipse(-28,-50,6,6,'#efc09b');ellipse(-2,-112,25,27,'#efc6a1');ctx.beginPath();ctx.arc(-2,-117,25,Math.PI,Math.PI*2);ctx.fillStyle='#70563e';ctx.fill();round(-28,-124,11,23,5,'#70563e');ellipse(-24,-107,5,7,'#eab991');ellipse(8,-107,2,2.5,'#5a4a39');ellipse(-8,-107,2,2.5,'#5a4a39');ellipse(14,-100,4,2.4,'#eaaa88');ctx.beginPath();ctx.arc(0,-102,5,.25,2.7);ctx.strokeStyle='#a87555';ctx.lineWidth=1.6;ctx.stroke();ellipse(-2,-137,39,8,'#ebd2a0');round(-27,-164,51,28,12,'#f2dfb4');round(-27,-146,51,7,2,'#96a76b');ellipse(12,-148,6,3,'#f5b19a');
// The open basket is carried on the character's back, at the right shoulder.
ctx.beginPath();ctx.ellipse(29,-73,27,23,0,Math.PI,Math.PI*2);ctx.strokeStyle='#b68b50';ctx.lineWidth=4;ctx.stroke();path([[0,-81],[61,-81],[54,-34],[8,-34]],'#c99d5e','#a37c47',2);for(let i=0;i<4;i++)line(6,-72+i*10,57-i*.9,-72+i*10,'#e0b674',3);for(let i=0;i<6;i++)line(10+i*8,-77,13+i*7,-36,'#b8894e',1.3);ellipse(30,-81,31,7,'#a87e47');ellipse(30,-82,25,4,'#71593a');ctx.restore();}
function basketX(){return playerX+30;}function basketY(){return H-139;}
function updateHud(){ui.score.textContent=score;[...ui.hearts.children].forEach((h,i)=>h.classList.toggle('lost',i>=lives));ui.hearts.setAttribute('aria-label',`剩餘 ${lives} 顆心`);}
function showOverlay(kind){ui.overlay.hidden=false;if(kind==='ready'){ui.title.textContent='今天，一起接蘋果！';ui.badge.textContent='小松鼠的午後邀請';ui.copy.innerHTML='籃子準備好了嗎？<br>接住蘋果，記得閃開刺刺栗子。';ui.play.textContent='開始收集 →';ui.tip.textContent='三顆愛心・一籃子的好心情';}else if(kind==='paused'){ui.title.textContent='果園休息一下';ui.badge.textContent='蘋果等你回來';ui.copy.textContent=`目前收集了 ${score} 分，還有 ${lives} 顆心。`;ui.play.textContent='繼續收集 →';ui.tip.textContent='點一下繼續，或按空白鍵';}else{ui.title.textContent='今天收穫了 '+score+' 分！';ui.badge.textContent='這一籃，是你的努力';ui.copy.innerHTML='三顆愛心都用完了。<br>小松鼠還想再和你玩一次！';ui.play.textContent='再玩一次 →';ui.tip.textContent='下一籃，也會裝滿小快樂';}}
function tone(freq,duration=.09,type='sine',delay=0){if(!soundOn)return;try{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),at=audioCtx.currentTime+delay;osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(.035,at);gain.gain.exponentialRampToValueAtTime(.001,at+duration);osc.connect(gain);gain.connect(audioCtx.destination);osc.start(at);osc.stop(at+duration+.01);}catch{soundOn=false;}}
function clearControls(){keys.clear();held.clear();pointerTarget=null;dragging=false;$('left').classList.remove('active');$('right').classList.remove('active');}
function startGame(){clearControls();score=0;lives=3;items=[];particles=[];popups=[];playerX=W/2-18;previousX=playerX;nextDrop=.9;hurt=0;throwTime=0;squirrelX=W*.52;squirrelTarget=squirrelX;mode='playing';pausedForHidden=false;ui.overlay.hidden=true;ui.start.textContent='暫停';ui.status.textContent='接蘋果 ＋1 分，躲栗子護愛心';updateHud();ui.announcer.textContent='遊戲開始，三顆心，零分。';tone(440,.12);tone(660,.12,'sine',.1);lastTime=performance.now();}
function pauseGame(auto=false){if(mode!=='playing')return;mode='paused';pausedForHidden=auto;clearControls();ui.start.textContent='繼續';ui.status.textContent='已暫停，果子也休息一下';showOverlay('paused');}
function resumeGame(){if(mode!=='paused')return;mode='playing';pausedForHidden=false;ui.overlay.hidden=true;ui.start.textContent='暫停';ui.status.textContent='接蘋果 ＋1 分，躲栗子護愛心';clearControls();lastTime=performance.now();}
function finish(){mode='ended';clearControls();ui.start.textContent='開始遊戲';ui.status.textContent='收穫完成，再接一籃蘋果吧！';showOverlay('ended');ui.announcer.textContent=`遊戲結束，得到 ${score} 分。`;tone(330,.16);tone(247,.24,'sine',.17);}
function burst(x,y,color,count=9){if(reduceMotion)return;for(let i=0;i<count;i++)particles.push({x,y,vx:rnd(-65,65),vy:rnd(-135,-30),life:.65,ttl:.65,r:rnd(2,4),color});}
function loseHeart(x,y,reason){lives=Math.max(0,lives-1);hurt=.65;burst(x,y,'#e9947b',6);popups.push({x:clamp(x,45,W-45),y,text:'−1 ♥',color:'#b36c50',life:1,ttl:1});updateHud();ui.announcer.textContent=`${reason}，剩餘 ${lives} 顆心。`;tone(190,.13,'triangle');if(lives===0)finish();}
function resolveItem(item,caught){if(item.type==='apple'){if(caught){score++;burst(item.x,basketY(),'#f6db88');popups.push({x:item.x,y:basketY()-20,text:'＋1',color:'#617d43',life:.9,ttl:.9});updateHud();tone(620,.08);tone(820,.07,'sine',.07);}else loseHeart(item.x,H-55,'漏接蘋果');}else if(caught)loseHeart(item.x,basketY(),'接到栗子');else burst(item.x,H-55,'#a3b16a',4);}
function drop(){const x=rnd(42,W-42);squirrelTarget=x;throwTime=.45;const type=Math.random()<.8?'apple':'chestnut';items.push({x,y:105,prevY:105,type,r:type==='apple'?16:20,vy:rnd(100,132)+Math.min(score*1.7,42),angle:rnd(-.25,.25),spin:rnd(-.65,.65)});}
function step(dt){clock+=dt;if(throwTime>0)throwTime=Math.max(0,throwTime-dt);squirrelX+=(squirrelTarget-squirrelX)*Math.min(1,dt*10);if(mode!=='playing')return;hurt=Math.max(0,hurt-dt);previousX=playerX;const left=keys.has('ArrowLeft')||keys.has('a')||[...held.values()].includes(-1),right=keys.has('ArrowRight')||keys.has('d')||[...held.values()].includes(1);let dir=(right?1:0)-(left?1:0);if(dir){playerX+=dir*355*dt;pointerTarget=null;}else if(pointerTarget!==null){const diff=pointerTarget-playerX;playerX+=clamp(diff,-620*dt,620*dt);}playerX=clamp(playerX,35,W-66);if(Math.abs(playerX-previousX)>.1)walk+=dt*13;nextDrop-=dt;if(nextDrop<=0){drop();nextDrop=rnd(.92,1.25)-Math.min(score*.006,.2);}const rim=basketY();for(let i=items.length-1;i>=0;i--){const item=items[i];item.prevY=item.y;item.vy+=dt*22;item.y+=item.vy*dt;item.angle+=item.spin*dt;
// Sweep against the basket mouth so fast frames cannot skip a catch.
const prevBottom=item.prevY+item.r,bottom=item.y+item.r;let caught=false;if(prevBottom<=rim&&bottom>=rim){const fraction=clamp((rim-prevBottom)/(bottom-prevBottom||1),0,1),atX=previousX+(playerX-previousX)*fraction+30;caught=Math.abs(item.x-atX)<25+item.r*.5;}if(caught||item.y-item.r>H-49){items.splice(i,1);resolveItem(item,caught);if(mode==='ended')break;}}
for(let i=particles.length-1;i>=0;i--){let p=particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=220*dt;if(p.life<=0)particles.splice(i,1);}for(let i=popups.length-1;i>=0;i--){let p=popups[i];p.life-=dt;p.y-=38*dt;if(p.life<=0)popups.splice(i,1);}}
function render(){ctx.clearRect(0,0,W,H);background();squirrel();for(const it of items){if(it.type==='apple')apple(it.x,it.y,it.r,it.angle,true);else chestnut(it.x,it.y,it.r,it.angle);}player();for(const p of particles){ctx.globalAlpha=p.life/p.ttl;ellipse(p.x,p.y,p.r,p.r,p.color);}ctx.globalAlpha=1;for(const p of popups){ctx.save();ctx.globalAlpha=Math.min(1,p.life*2);ctx.font='900 22px "Microsoft JhengHei",sans-serif';ctx.textAlign='center';ctx.fillStyle=p.color;ctx.strokeStyle='#fff9ed';ctx.lineWidth=4;ctx.strokeText(p.text,p.x,p.y);ctx.fillText(p.text,p.x,p.y);ctx.restore();}}
function resize(){const rect=stage.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2),oldW=W;W=rect.width/rect.height*H;canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(canvas.width/W,0,0,canvas.height/H,0,0);playerX=clamp(playerX*(W/oldW),35,W-66);previousX=playerX;items.forEach(i=>i.x=clamp(i.x*(W/oldW),30,W-30));squirrelX=clamp(squirrelX*(W/oldW),42,W-42);squirrelTarget=clamp(squirrelTarget*(W/oldW),42,W-42);pointerTarget=null;render();}
function frame(now){const dt=lastTime?Math.min((now-lastTime)/1000,.04):0;lastTime=now;if(!document.hidden){step(dt);render();}requestAnimationFrame(frame);}
ui.start.addEventListener('click',()=>{if(mode==='playing')pauseGame();else if(mode==='paused')resumeGame();else startGame();});ui.restart.addEventListener('click',startGame);ui.play.addEventListener('click',()=>mode==='paused'?resumeGame():startGame());
addEventListener('keydown',e=>{const key=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowLeft','ArrowRight','a','d'].includes(key)){if(mode==='playing'){e.preventDefault();keys.add(key);}}if(e.code==='Space'&&!e.repeat&&e.target.tagName!=='BUTTON'){e.preventDefault();if(mode==='playing')pauseGame();else if(mode==='paused')resumeGame();else startGame();}});addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));addEventListener('blur',()=>pauseGame());document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseGame(true);});
function pointerMove(e){if(mode!=='playing')return;const rect=stage.getBoundingClientRect();pointerTarget=clamp((e.clientX-rect.left)/rect.width*W-30,35,W-66);}
stage.addEventListener('pointerdown',e=>{if(mode!=='playing'||e.target!==canvas)return;dragging=true;stage.setPointerCapture(e.pointerId);pointerMove(e);});stage.addEventListener('pointermove',e=>{if(e.pointerType==='mouse'||dragging)pointerMove(e);});stage.addEventListener('pointerup',()=>dragging=false);stage.addEventListener('pointercancel',()=>{dragging=false;pointerTarget=null;});
for(const [id,dir] of [['left',-1],['right',1]]){const b=$(id);b.addEventListener('pointerdown',e=>{e.preventDefault();if(mode!=='playing')return;b.setPointerCapture(e.pointerId);held.set(e.pointerId,dir);b.classList.add('active');});const release=e=>{held.delete(e.pointerId);b.classList.remove('active');};b.addEventListener('pointerup',release);b.addEventListener('pointercancel',release);b.addEventListener('lostpointercapture',release);}
ui.sound.addEventListener('click',()=>{soundOn=!soundOn;ui.sound.setAttribute('aria-pressed',String(soundOn));ui.sound.setAttribute('aria-label',soundOn?'關閉音效':'開啟音效');ui.sound.title=soundOn?'關閉音效':'開啟音效';ui.sound.style.background=soundOn?'#dbeacb':'';tone(600,.08);});
new ResizeObserver(resize).observe(stage);updateHud();resize();requestAnimationFrame(frame);
})();
